# ======================================================
#  Test configuration for Webserv error testing
#  Target directory: ./www/testsite
# ======================================================

server {
    listen 0.0.0.0:8081;
    server_name tests.local;
    root ./www/testsite;
    index index.html;
    autoindex off;

    # Max body size used for 413 testing
    client_max_body_size 2M;

    # Timeout behavior (408 testing)
    timeout 1s;

    location /only_post {
        limit_except POST;
    }

    location /only_delete {
        limit_except DELETE;
    }

    location /redirect1 {
        return 301 https://youtube.com;
    }

    location /redirect2 {
        return 302 https://muxxu.com;
    }
}
